name: didrikstad
options:
  deploymentTarget:
    iOS: "15.0"
targets:
  didrikstad:
    type: application
    platform: iOS
    sources: [didrikstad]
    scheme: {}
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.swstl.didrikstad
        GENERATE_INFOPLIST_FILE: YES
        INFOPLIST_KEY_UILaunchScreen_Generation: YES
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
